# define base image
FROM python:3.6

# set working directory
WORKDIR /jupyterlab/notebooks

ENV TZ="America/Sao_Paulo"\
    JUPYTER_TOKEN="vert@2020"
	
# run command at build time
RUN pip install --no-cache-dir --disable-pip-version-check jupyterlab \
    && pip install --no-cache-dir --disable-pip-version-check swat==1.6.1 \
    && pip install --no-cache-dir --disable-pip-version-check pdfplumber \
    && pip install --no-cache-dir --disable-pip-version-check PyPDF2 \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \	
	&& echo $TZ > /etc/timezone
	
EXPOSE 8888
CMD ["jupyter","lab","--ip=0.0.0.0", "--allow-root", "--no-browser"] #deploy jupyterlab	
